name: Commit CI

on:
  push:
    branches: [ main, master]
    paths:
      - 'src/*'
    tags:
      - '![0-9]+.*'
  pull_request:
  workflow_dispatch:


jobs:
  dict-packs-build:
    uses: ./.github/workflows/dict-packs-build.yml
