name: Release CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/dict-packs-build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 获取构件
        uses: actions/download-artifact@v3
        with:
          name: ShanRenMaLTS-Win-Release
          path: ./Release/build

      - name: 打包方案
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 ShanRenMaLTS-${{ github.ref_name }}-Win.7z ./Release/build/.

      - name: 版本发布
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ShanRenMaLTS-${{ github.ref_name }}-Win.7z"
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}